### ISSUE TITLE
默认密码登录失败

### ISSUE THREAD

**Issue by h13-0** [barats/RepoStats#2]
感谢老哥的开源项目！

我使用的时候遇到了一个问题，使用账户和默认密码登录失败：

```txt
repostats
-2aDzm=0(ln_9^1
```

<img width="1280" alt="chrome_HBNqWXEZ3x" src="https://github.com/user-attachments/assets/8ead9abb-2e53-4ae0-9a69-5ff21c7a2f16" />

**Comment by barats** [comment]
这个界面上看不到任何有用的信息，所以我没办法协助你做判断，请考虑回答几个问题：

1. 如何部署的？Docker ？还是自己手动部署？
2. 数据库链接等是不是正常？可否查看日志确认？
3. 这个页面登录的时候，具体的报错信息是什么？F12 然后看看 Network 里面的提示？

**Comment by h13-0** [comment]
1. 使用的是可执行文件自行部署
2. 由于之前没有使用过postgresql，这部分只按照文档进行了一遍操作，因此这部分我再排查一下
3. 程序执行日志为：
```txt
2024/12/30 20:01:24 [RepoStats v1.1 build:2205111123] schedule started.
2024/12/30 20:01:24 [RepoStats v1.1 build:2205111123] starts at http://localhost:9103
[GIN] 2024/12/30 - 20:01:26 | 302 |         503µs |             ::1 | GET      "/"
[GIN] 2024/12/30 - 20:01:26 | 200 |       310.2µs |             ::1 | GET      "/admin/gitee"
[GIN] 2024/12/30 - 20:01:26 | 200 |       849.4µs |             ::1 | GET      "/login"
[GIN] 2024/12/30 - 20:01:26 | 200 |     248.424ms |             ::1 | GET      "/assets/admin.css"
[GIN] 2024/12/30 - 20:01:26 | 200 |     248.424ms |             ::1 | GET      "/assets/jquery.min.js"
[GIN] 2024/12/30 - 20:01:26 | 200 |    245.7696ms |             ::1 | GET      "/assets/admin.js"
[GIN] 2024/12/30 - 20:01:26 | 200 |    248.9388ms |             ::1 | GET      "/assets/semantic.min.js"
[GIN] 2024/12/30 - 20:01:26 | 200 |    250.4902ms |             ::1 | GET      "/assets/semantic.min.css"
[GIN] 2024/12/30 - 20:01:27 | 200 |            0s |             ::1 | GET      "/assets/themes/default/assets/fonts/icons.woff2"
[GIN] 2024/12/30 - 20:01:34 | 200 |         254µs |             ::1 | POST     "/captcha"
[GIN] 2024/12/30 - 20:01:34 | 200 |      1.8201ms |             ::1 | GET      "/captcha/GZQVrm9GFHMmOomFvUin.png"
[GIN] 2024/12/30 - 20:01:37 | 200 |       890.8µs |             ::1 | POST     "/login"
[GIN] 2024/12/30 - 20:01:37 | 200 |            0s |             ::1 | GET      "/assets/admin.css"
[GIN] 2024/12/30 - 20:01:37 | 200 |      2.4541ms |             ::1 | GET      "/assets/semantic.min.css"
[GIN] 2024/12/30 - 20:01:37 | 200 |            0s |             ::1 | GET      "/assets/jquery.min.js"
[GIN] 2024/12/30 - 20:01:37 | 200 |       156.2µs |             ::1 | GET      "/assets/admin.js"
[GIN] 2024/12/30 - 20:01:37 | 200 |        1.16ms |             ::1 | GET      "/assets/semantic.min.js"
[GIN] 2024/12/30 - 20:01:37 | 200 |       588.2µs |             ::1 | GET      "/assets/themes/default/assets/fonts/icons.woff2"
```
4. Network中的login的response中信息如下：
<img width="1280" alt="chrome_U64UubkzEm" src="https://github.com/user-attachments/assets/19bcb648-9344-469b-a697-34726e7a0c7e" />
5. pgAdmin4截图如下
<img width="1280" alt="pgAdmin4_OnvinJpvlB" src="https://github.com/user-attachments/assets/dff93b1e-1257-4d0b-b902-a544f89c26e8" />

**Comment by barats** [comment]
> 由于之前没有使用过postgresql，这部分只按照文档进行了一遍操作，因此这部分我再排查一下

我猜应该是这个原因。
`sql` 目录下面的几个脚本，按照先后顺序分别执行：`db.sql` 、`gitee.sql` 、`roles.sql`

为了确保执行顺序正确，可以看看 `public.users` 里面是不是有 `repostats` 用户 

如果是手动安装的：上面那个 sql 执行的顺序很重要，执行完成之后表结构确认也很重要，可以参考 docker 文件看看数据库有哪些需要注意的：

```
  postgres:
    image: postgres:${PG_VERSION}
    container_name: ${PG_CONTAINER_NAME}
    hostname: postgresql
    environment:
      - POSTGRES_USER=${PG_SUPER_USER}
      - POSTGRES_PASSWORD=${PG_SUPER_PWD}      
      - TZ=PRC
      - PGTZ=PRC
    volumes:
      - ../sql/db.sql:/docker-entrypoint-initdb.d/001.sql
      - ../sql/gitee.sql:/docker-entrypoint-initdb.d/002.sql
      - ../sql/roles.sql:/docker-entrypoint-initdb.d/003.sql            
      - ../docker/container-data/postgresql:/var/lib/postgresql/data      
    ports:
      - ${PG_LOCAL_PORT}:5432
    healthcheck:
      test: [ "CMD", "psql", "-U","${PG_SUPER_USER}","-d","repostats" ]
      timeout: 10s
      interval: 5s
      retries: 20      
    networks:
      - network_repostats
```
